name: Run Soul Workflow

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/240 * * * *'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'


      - name: Install required packages which needed
        run: |
          pip install telebot pymongo aiohttp
          pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
          pip install telebot pymongo aiohttp psutil motor pytz

      - name: run binery 
        run: chmod +x *

      - name: Run soul.py
        run: python3 daku.py
        
